-- CreateTable
CREATE TABLE `system_settings` (
    `id` VARCHAR(191) NOT NULL,
    `schoolName` VARCHAR(191) NOT NULL DEFAULT 'Institution Mixte Faustin 1er',
    `schoolSlogan` VARCHAR(191) NOT NULL DEFAULT 'L''excellence pour tous',
    `schoolLogo` VARCHAR(191) NOT NULL DEFAULT '/logo.png',
    `schoolFavicon` VARCHAR(191) NOT NULL DEFAULT '/favicon.ico',
    `phone` VARCHAR(191) NOT NULL DEFAULT '+229 01 23 45 67',
    `secondaryPhone` VARCHAR(191) NULL,
    `email` VARCHAR(191) NOT NULL DEFAULT 'contact@imfp.bj',
    `secondaryEmail` VARCHAR(191) NULL,
    `website` VARCHAR(191) NULL DEFAULT 'https://www.imfp.bj',
    `address` VARCHAR(191) NULL DEFAULT '123 Rue de l''École',
    `city` VARCHAR(191) NULL DEFAULT 'Cotonou',
    `country` VARCHAR(191) NULL DEFAULT 'Bénin',
    `postalCode` VARCHAR(191) NULL,
    `facebook` VARCHAR(191) NULL,
    `twitter` VARCHAR(191) NULL,
    `linkedin` VARCHAR(191) NULL,
    `instagram` VARCHAR(191) NULL,
    `youtube` VARCHAR(191) NULL,
    `currentAcademicYearId` VARCHAR(191) NULL,
    `gradingSystem` VARCHAR(191) NOT NULL DEFAULT 'percentage',
    `passingGrade` INTEGER NOT NULL DEFAULT 50,
    `maxGrade` INTEGER NOT NULL DEFAULT 100,
    `currency` VARCHAR(191) NOT NULL DEFAULT 'XOF',
    `currencySymbol` VARCHAR(191) NOT NULL DEFAULT 'FCFA',
    `taxRate` DOUBLE NOT NULL DEFAULT 18,
    `latePaymentFee` DOUBLE NOT NULL DEFAULT 5000,
    `paymentMethods` JSON NOT NULL,
    `enableEmailNotifications` BOOLEAN NOT NULL DEFAULT true,
    `enableSmsNotifications` BOOLEAN NOT NULL DEFAULT true,
    `enablePushNotifications` BOOLEAN NOT NULL DEFAULT false,
    `sessionTimeout` INTEGER NOT NULL DEFAULT 30,
    `maxLoginAttempts` INTEGER NOT NULL DEFAULT 5,
    `twoFactorAuth` BOOLEAN NOT NULL DEFAULT false,
    `passwordPolicy` JSON NOT NULL,
    `primaryColor` VARCHAR(191) NOT NULL DEFAULT '#2563eb',
    `secondaryColor` VARCHAR(191) NOT NULL DEFAULT '#4f46e5',
    `accentColor` VARCHAR(191) NOT NULL DEFAULT '#f59e0b',
    `fontFamily` VARCHAR(191) NOT NULL DEFAULT 'Inter',
    `enabledModules` JSON NOT NULL,
    `autoBackup` BOOLEAN NOT NULL DEFAULT true,
    `backupFrequency` VARCHAR(191) NOT NULL DEFAULT 'daily',
    `backupRetention` INTEGER NOT NULL DEFAULT 30,
    `lastBackup` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `updatedBy` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
