/**
 * @file backupService.ts
 * @description Service pour la gestion des sauvegardes
 * @module Services/Backup
 */

import { exec } from "child_process";
import { promisify } from "util";
import fs from "fs";
import path from "path";
import prisma from "../prisma";
import { createConnection } from "mysql2/promise";

const execAsync = promisify(exec);

/**
 * @class BackupService
 * @description Service pour la gestion des sauvegardes de base de données
 */
export class BackupService {
  /**
   * Crée une sauvegarde complète de la base de données
   */
  static async createBackup(data: {
    name?: string;
    modules?: string[];
    userId?: string;
  }) {
    const { name, modules, userId } = data;
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const backupDir = path.join(__dirname, "../../backups");

    // Créer le dossier de sauvegarde s'il n'existe pas
    if (!fs.existsSync(backupDir)) {
      fs.mkdirSync(backupDir, { recursive: true });
    }

    const dbUrl = process.env.DATABASE_URL;
    if (!dbUrl) {
      throw {
        status: 500,
        message: "DATABASE_URL non configurée",
      };
    }

    const sqlFilename = name
      ? `backup-${name.replace(/[^a-zA-Z0-9]/g, "-")}-${timestamp}.sql`
      : `backup-academic-${timestamp}.sql`;

    const sqlFilePath = path.join(backupDir, sqlFilename);

    console.log(`🔧 Création de la sauvegarde MySQL (Node.js): ${sqlFilename}`);

    // Extraire les informations de connexion
    const urlMatch = dbUrl.match(
      /mysql:\/\/([^:]+):([^@]+)@([^:]+):(\d+)\/(.+)/
    );
    if (!urlMatch) {
      throw new Error("Format DATABASE_URL MySQL invalide");
    }

    const [, username, password, host, port, database] = urlMatch;

    let connection;
    try {
      // Créer une connexion
      connection = await createConnection({
        host,
        port: parseInt(port),
        user: username,
        password,
        database,
        charset: "utf8mb4",
      });

      let sqlContent = `-- MySQL dump generated by Academic System\n`;
      sqlContent += `-- Server version: Node.js MySQL2\n`;
      sqlContent += `-- Database: ${database}\n`;
      sqlContent += `-- Generation Time: ${new Date().toISOString()}\n\n`;
      sqlContent += `SET FOREIGN_KEY_CHECKS=0;\n\n`;

      // Récupérer la liste des tables
      const [tables] = (await connection.execute(
        `SELECT table_name FROM information_schema.tables 
         WHERE table_schema = ? AND table_type = 'BASE TABLE'`,
        [database]
      )) as any[];

      console.log(`📊 Tables trouvées: ${tables.length}`);

      for (const table of tables) {
        const tableName = table.TABLE_NAME;

        // Structure de la table
        const [createTable] = (await connection.execute(
          `SHOW CREATE TABLE \`${tableName}\``
        )) as any[];

        sqlContent += `--\n-- Table structure for table \`${tableName}\`\n--\n\n`;
        sqlContent += `DROP TABLE IF EXISTS \`${tableName}\`;\n`;
        sqlContent += `${createTable[0]["Create Table"]};\n\n`;

        // Données de la table
        const [rows] = (await connection.execute(
          `SELECT * FROM \`${tableName}\``
        )) as any[];

        if (rows.length > 0) {
          sqlContent += `--\n-- Dumping data for table \`${tableName}\`\n--\n\n`;
          sqlContent += `LOCK TABLES \`${tableName}\` WRITE;\n`;

          for (const row of rows) {
            const columns = Object.keys(row)
              .map((col) => `\`${col}\``)
              .join(", ");
            const values = Object.values(row)
              .map((value) => {
                if (value === null) return "NULL";
                if (typeof value === "string")
                  return `'${value.replace(/'/g, "''")}'`;
                if (value instanceof Date)
                  return `'${value.toISOString().slice(0, 19).replace("T", " ")}'`;
                return value;
              })
              .join(", ");

            sqlContent += `INSERT INTO \`${tableName}\` (${columns}) VALUES (${values});\n`;
          }

          sqlContent += `UNLOCK TABLES;\n\n`;
        }
      }

      sqlContent += `SET FOREIGN_KEY_CHECKS=1;\n`;
      sqlContent += `-- Dump completed on ${new Date().toISOString()}\n`;

      // Écrire le fichier
      fs.writeFileSync(sqlFilePath, sqlContent, "utf8");
      const stats = fs.statSync(sqlFilePath);

      // Compter les enregistrements pour les métadonnées
      const recordCounts = {
        students: await prisma.student.count(),
        professors: await prisma.professeur.count(),
        users: await prisma.user.count(),
        subjects: await prisma.subject.count(),
        enrollments: await prisma.enrollment.count(),
        assignments: await prisma.classAssignment.count(),
        grades: await prisma.grade.count(),
        payments: await prisma.feePayment.count(),
        auditLogs: await prisma.auditLog.count(),
      };

      const totalRecords = Object.values(recordCounts).reduce(
        (a, b) => a + b,
        0
      );

      const backup = {
        filename: sqlFilename,
        size: stats.size,
        timestamp: new Date().toISOString(),
        records: recordCounts,
        name: name || null,
        modules: modules || null,
      };

      // Sauvegarder les métadonnées
      const metadataPath = path.join(backupDir, `${sqlFilename}.meta.json`);
      fs.writeFileSync(metadataPath, JSON.stringify(backup, null, 2));

      console.log(
        `✅ Sauvegarde créée: ${sqlFilename} (${stats.size} bytes, ${totalRecords} enregistrements)`
      );

      return {
        success: true,
        message: "Sauvegarde créée avec succès",
        data: backup,
        metadata: {
          fileSize: stats.size,
          totalRecords,
          tablesExported: tables.length,
        },
      };
    } finally {
      if (connection) {
        try {
          await connection.end();
        } catch (error) {
          console.error("Erreur fermeture connexion:", error);
        }
      }
    }
  }

  /**
   * Génère un export SQL simplifié
   */
  static async exportSQL(userId?: string) {
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const backupDir = path.join(__dirname, "../../backups");

    if (!fs.existsSync(backupDir)) {
      fs.mkdirSync(backupDir, { recursive: true });
    }

    const filename = `export-academic-${timestamp}.sql`;
    const filepath = path.join(backupDir, filename);

    // Générer un export basique
    let sqlContent = `-- Academic System SQL Export\n`;
    sqlContent += `-- Generated: ${new Date().toISOString()}\n\n`;

    // Ajouter des informations système
    sqlContent += `-- Database Statistics:\n`;

    const counts = {
      students: await prisma.student.count(),
      professors: await prisma.professeur.count(),
      users: await prisma.user.count(),
      subjects: await prisma.subject.count(),
    };

    for (const [table, count] of Object.entries(counts)) {
      sqlContent += `-- ${table}: ${count} records\n`;
    }

    sqlContent += `\n-- Export completed successfully\n`;

    fs.writeFileSync(filepath, sqlContent, "utf8");
    const stats = fs.statSync(filepath);

    return {
      success: true,
      data: {
        filename,
        path: filepath,
        size: stats.size,
        timestamp: new Date().toISOString(),
      },
      metadata: {
        counts,
      },
    };
  }

  /**
   * Liste toutes les sauvegardes disponibles
   */
  static async listBackups() {
    const backupDir = path.join(__dirname, "../../backups");

    if (!fs.existsSync(backupDir)) {
      fs.mkdirSync(backupDir, { recursive: true });
      return {
        backups: [],
        stats: {
          total: 0,
          totalSize: 0,
          available: 0,
          missing: 0,
        },
      };
    }

    const files = fs.readdirSync(backupDir);
    const backups = [];
    let totalSize = 0;

    for (const file of files) {
      if (file.endsWith(".meta.json")) {
        const metaPath = path.join(backupDir, file);
        try {
          const metaData = JSON.parse(fs.readFileSync(metaPath, "utf8"));

          // Vérifier que le fichier SQL correspondant existe
          const sqlFilename = file.replace(".meta.json", "");
          const sqlFilePath = path.join(backupDir, sqlFilename);

          if (fs.existsSync(sqlFilePath)) {
            const stats = fs.statSync(sqlFilePath);
            metaData.size = stats.size;
            metaData.exists = true;
            backups.push(metaData);
            totalSize += stats.size;
          } else {
            metaData.exists = false;
            backups.push(metaData);
          }
        } catch (error) {
          console.error(`❌ Erreur lecture metadata ${file}:`, error);
        }
      }
    }

    // Trier par date (plus récent en premier)
    backups.sort(
      (a, b) =>
        new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
    );

    const stats = {
      total: backups.length,
      totalSize,
      available: backups.filter((b) => b.exists).length,
      missing: backups.filter((b) => !b.exists).length,
    };

    return {
      backups,
      stats,
    };
  }

  /**
   * Récupère les statistiques de la base de données et des sauvegardes
   */
  static async getBackupStats() {
    const recordCounts = {
      students: await prisma.student.count(),
      professors: await prisma.professeur.count(),
      users: await prisma.user.count(),
      subjects: await prisma.subject.count(),
      enrollments: await prisma.enrollment.count(),
      assignments: await prisma.classAssignment.count(),
      grades: await prisma.grade.count(),
      payments: await prisma.feePayment.count(),
      auditLogs: await prisma.auditLog.count(),
    };

    const totalRecords = Object.values(recordCounts).reduce((a, b) => a + b, 0);

    // Statistiques des fichiers de sauvegarde
    const backupDir = path.join(__dirname, "../../backups");
    let backupStats: {
      total: number;
      totalSize: number;
      lastBackup: string | null;
    } = { total: 0, totalSize: 0, lastBackup: null };

    if (fs.existsSync(backupDir)) {
      const files = fs.readdirSync(backupDir);
      const sqlFiles = files.filter(
        (f) => f.endsWith(".sql") && !f.endsWith(".meta.json")
      );

      backupStats.total = sqlFiles.length;

      for (const file of sqlFiles) {
        const filePath = path.join(backupDir, file);
        const stats = fs.statSync(filePath);
        backupStats.totalSize += stats.size;
      }

      // Dernière sauvegarde
      if (sqlFiles.length > 0) {
        const latestFile = sqlFiles
          .map((f) => ({
            name: f,
            time: fs.statSync(path.join(backupDir, f)).mtime,
          }))
          .sort((a, b) => b.time.getTime() - a.time.getTime())[0];

        backupStats.lastBackup = latestFile.time.toISOString();
      }
    }

    return {
      database: {
        totalRecords,
        ...recordCounts,
      },
      backups: backupStats,
    };
  }

  /**
   * Télécharge une sauvegarde spécifique
   */
  static async downloadBackup(filename: string) {
    const backupDir = path.join(__dirname, "../../backups");
    const sqlFilePath = path.join(backupDir, filename);
    const metadataPath = path.join(backupDir, `${filename}.meta.json`);

    // Vérifier que le fichier SQL existe
    if (!fs.existsSync(sqlFilePath)) {
      throw {
        status: 404,
        message: "Fichier de sauvegarde non trouvé",
      };
    }

    const stats = fs.statSync(sqlFilePath);

    // Lire les métadonnées si elles existent
    let metadata = null;
    if (fs.existsSync(metadataPath)) {
      try {
        metadata = JSON.parse(fs.readFileSync(metadataPath, "utf8"));
      } catch (error) {
        console.error("Erreur lecture métadonnées:", error);
      }
    }

    return {
      success: true,
      data: {
        filepath: sqlFilePath,
        filename,
        size: stats.size,
        stats,
        metadata,
      },
    };
  }

  /**
   * Supprime une sauvegarde
   */
  static async deleteBackup(filename: string) {
    const backupDir = path.join(__dirname, "../../backups");

    const sqlFilePath = path.join(backupDir, filename);
    const metadataPath = path.join(backupDir, `${filename}.meta.json`);

    console.log(`🗑️ Suppression de la sauvegarde: ${filename}`);

    const deletedFiles = [];

    // Supprimer le fichier SQL
    if (fs.existsSync(sqlFilePath)) {
      fs.unlinkSync(sqlFilePath);
      deletedFiles.push(sqlFilePath);
    }

    // Supprimer les métadonnées
    if (fs.existsSync(metadataPath)) {
      fs.unlinkSync(metadataPath);
      deletedFiles.push(metadataPath);
    }

    return {
      success: true,
      message: "Sauvegarde supprimée avec succès",
      data: {
        filename,
        deletedFiles,
        sqlDeleted: fs.existsSync(sqlFilePath) === false,
        metadataDeleted: fs.existsSync(metadataPath) === false,
      },
    };
  }
}
